Test commit
JetBrains-Research/cuBool pull request #1
Opened 2020-12-10 17:41 UTC by Krekep

Добавлена первая версия питон обёртки. К сожалению, у себя протестировать не могу.
Также стоит вопрос про стиль написания кода, надо ли что-то менять?

2020-12-10 19:57 UTC, EgorOrachyov commented
Для на прототипа нормально. Но надо поменять несколько вещей. 
Мы обсуждали, что нам необходимо API, похожее на pygraphblas (ссылку я прикреплял в readme в репо).
Это касается примитивов и схемы управления ресурсами. Поэтому еще потребуется:

- В папку pycubool добавить `__init__.py` файл, который булет ответсвеннен за сетап библиотеки при импорте. Наша цель здесь зделать следующее:
 1.) создать python класс, который будет хранить декларации вызовов ctypes, чтобы не объявлять их
      каждый раз при вызове какой-либо функции
 2.) создать класс, который пуддет поддерживать как раз таки этот ctypes wrapper, а также хранить 
    инстанс CuBoolInstance, который внутри под капотом будет передавать внутрь библиотекчных функций
 3.) добавить событие выхода из приложения, при котором ресурсы (инстанс и библиотека) будут корректно закрыты

- Добавить отдельные файлы для всяких утилит, типа код ошибок (по типу pygraphblas)
- Добавить класс, который обернет в себя функциональность матрицы (по типу pygraphblas)
- Добавить по файлу на оперкации `add`, `kron`, 'mxm'
- Ипользовать нотацию в духе `pycubool.Matrix`  вместо `pycubool.CuBool_Matrix` тк это слишком избыточно
- Использовать `__del__` для освобождения ресурсов (опять же, см python/pycubool/README.md)

Идея того, как сделать загрузку и выгрузку библиотеки и инстанса:
![image](https://user-images.githubusercontent.com/31863304/101822815-f89b4780-3b3a-11eb-95b4-8a2d4edb81af.png)
![image](https://user-images.githubusercontent.com/31863304/101822895-123c8f00-3b3b-11eb-8389-5d1bb03f09ce.png)

2020-12-10 20:02 UTC, EgorOrachyov requested changes
См. Комментарий к PR.

2020-12-11 04:30 UTC, gsvgit requested changes
Согласен с комментариями Егора. Дополнительно (правда, несколько субъективно): не лучшая идея делать дебажную печать всегда. Лучше завести опциональный параметр типа debug или verbose с дефолтным значением false. Так-то это полезно и в боевом режиме уметь получить больше информации о процессе работы, но всегда забивать консоль отладочной печатью - зло.

2020-12-12 11:22 UTC, EgorOrachyov reviewed
Отлично. Есть пара моментов, на которые хотелось бы обратить внимание:

- `atexit` импортируется, но (вроде) нигде не используется
- файлы лучше именовать как myfancyfile.py строчными буквами (но это мы нигде особо не оговаривали)
- тесты, тестовые приложения лучше размещать в специальной отдельной папке
- импорты в стиле from a import * удобны, но снижают читаемость, я бы рекомендовал использовать алиасы
- папка `pycubool` была специально создана, чтобы разместить в ней все вайлы обретки, существование еще одной папки `CuBoolWrapper` внутри, которая не отвечает стандартам именования мне не ясно

Так как уже прилично сделано, вмерджу в мастер, посмотрю, работает ли, и далее уже в след. итерации добавим тесты, примеры использования и т.д.

2020-12-12 11:27 UTC, merged