Python tests review
JetBrains-Research/cuBool pull request #3
Opened 2021-02-22 16:16 UTC by Krekep

2021-02-24 16:16 UTC, EgorOrachyov requested changes
Посмотрел. Для начала весьма неплохо. Концепция в целом верная -- использование фреймворка для юнит тестов и сами тесты. Далее требуется доработать следующие моменты, постараюсь в порядке важности:

- Я недавно провел большой рефакторинг, структура файлов и методов для python поменялась, как и поменялась семантика использования некоторых методов. Поэтому придется это учесть и поправить.
- Входные данные для матриц не надо руками создавать, лучше для этого написать отдельные методы, которые будут эти данные генерировать, и операции эти наивно считать. Т.е. лучше создать еще файл `tests/test_utils` и туда добавить утилиты по типу: generate_matrix, kronecker, mxm и тд, которые будут на cpu считаться. Эти методы можно наивно реализовать, что то подобное, но для тестов с++ я уже делал в папке `cubool/utils/testing`. В целом, вдохновение для unit тестов из c++ можно в папке `cubool/tests` посмотреть.
- Необходимо разбить тесты крупных методов на отдельные файлы, т.е на тестирование каждого метода сделать отдельный файл: для kronecker, ewiseadd, mxm, build, transpose, reduce и т.д. должны быть отдельные файлы с тестами: `tests/test_matrix_kronecker`, `tests/test_matrix_mxm` и тд. Для простых методов типа nrows, nvals и тд можно оставить один файл `tests/test_matrix_metods`.
- Необхожимо удалить лишние файлы .idea из репозитория, тк это настройки именно твои локальные, их не должно быть в репо. Можешь для этого .gitignore настроить, хотя в репозитории вроде игнор .idea файлов уже настроен.

2021-02-27 09:00 UTC, EgorOrachyov commented
Поскольку мы хотим именно регрессионные тесты к python API сделать, возможно, в таком случае стоит входные матрицы для тестов, а так же результаты  посчитать отдельно, и хранить их в виде текстовых файлов.

- Перед тестом: загрузить из файла выходные данные и результат
- Запустить вычисление результата через pycubool
- Сравнить результат из pycubool с тем, что было в файле

Тогда не надо писать все те штуки, про которые я говорил: генерация данных, и реализация операций в python.

2021-02-27 12:15 UTC, Krekep commented
1. Прошу прощения за .idea файлы, не доглядел. 
2. Я так понял надо вынести в отдельные файлы тестирование операций над матрицами (сложение, умножение и т.д.), а что насчёт остальных, по типу транспонирования?
3. Для предпосчитанных матриц стоит завести отдельную папку в папке? Условно`tests\calculated`

2021-02-27 15:43 UTC, Krekep commented
Так, я чуть внимательнее перечитал, поэтому 2 вопрос перефразирую: в одном файле можно оставить всем тесты для свойств - `@property,` а тесты для остальных операций раскидать по отдельным файлам?

2021-02-28 12:34 UTC, EgorOrachyov commented
Да, все верно. Тесты по типу property, ну и другие более менее просты вещи в одном файле оставить, а операции крупные: умножение, сложение, транспонирование, подматрица и тд в отдельные файлы.

2021-02-28 12:35 UTC, EgorOrachyov commented
Для предпросчитаных матриц думаю стоит завести папку python/data (т.е отдельно от папки с самими тестами, чтобы не смешивать код и данные). Далее посмотрим, если что, то потом реструктурируем

2021-02-28 12:37 UTC, Krekep commented
Я написал тесты для всех методов для класса `Matrix`, за исключением:
- `Matrix.empty; Matrix.from_lists; matrix.build; matrix.to_string; matrix.__str__; matrix.__iter__; matrix.__getitem__; matrix.__init__; matrix.__del__;`
Сейчас матрицы для тестов читаются из папки `matrices` и имеют формат названия: *название метода.txt* и, соответственно *название метода_result.txt*. Если входных матриц несколько, то добавляется *_1, _2 и т.д.*

Матрицы имеют формат:
- Первая строка - два числа *n* и *m*, задающих размер матрицы.
- Вторая строка - список `rows`.
- Третья строка - списко `cols`.
Только для тестирования свойств `@property` другой формат входных данных - матрица `_result.txt` выглядит следующим образом:
- Первая строка - *n*.
- Вторая строка - *m*.
- Третья строка - *nvals*.
- Четвёртая строка - пара чисел, задающих форму `shape` матрицы.

2021-02-28 12:38 UTC, Krekep commented
Ох, я не заметил, что ты уже ответил. Хорошо, матрицы перемещу в другую папку.

2021-02-28 12:39 UTC, EgorOrachyov commented
Насчет формата матриц — возможно стоит их в формате mtx хранить, чтобы было более универсально. Там на первой стоке nrows ncols nvals, а далее на nvals строк пары чисел i j.

2021-02-28 12:40 UTC, Krekep commented
Понял, тогда чуть позже перепишу для mtx формата

2021-03-01 16:14 UTC, EgorOrachyov requested changes
@Krekep Посмотрел, что уже сейчас получается.
В целом, я бы предложил еще следующие доработки:

- Сейчас данные загружаются как `../data/......`, что будет работать, только если тесты запускаются из какой то определенной дирректории. Поэтому лучше вывести какую то глобальную переменную, типа `TestDataPathPrefix`, и далее делать `TestDataPathPrefix + / + matrix1.mtx` и тд.
- Как я понял, сейчас тольк по одному тесту, т.е. всего один такой комплект m1, m2, mResult для разных операций. А хотелось бы по несколько прогонов для каждой операции. В таком случае имена всех файлов с входными и выходными файлами видимо в списках должны быть 
- Было бы неплохо, если еще скрипты для генерации этих самых входных и выходных файлов тоже в репозитории были, скажем, в папке python/utils. Я предполагаю, что эти данные с помощью pycubool должны быть сгенерированы. Код генерации самих матриц тоже должен быть. Генерировать с помощью рандома можно, используя в качестве параметров размер матрицы, и плотность ее заполнения. Плотность заполнения `bydef` `nvals / (nrows * ncols) `

2021-03-06 16:40 UTC, Krekep commented
Могу ещё матрицы закомитить, но не уверен, что стоит.
У меня не сработало умножение матриц `mxm_generate.py`, упало с сигналом `11: SIGSEGV`, без дополнительных сообщений. При этом метод `transitive_closure` отработывает без проблем.
Все остальные методы работают без ошибок, и тесты к ним проходят.

2021-03-07 17:10 UTC, EgorOrachyov approved these changes

2021-03-07 17:11 UTC, merged